### ISSUE TITLE
Request send to https by default when using --rawdata

### ISSUE THREAD

**Issue by darshanpjpt** [hahwul/dalfox#452] opened 2023-03-03 06:47 UTC
## Describe the bug
when I use the raw request of http://testphp.vulnweb.com in dalfox, it sends request to https://testphp.vulnweb.com by default.

![image (1)](https://user-images.githubusercontent.com/71147956/222650645-38775d97-210c-4474-a51d-0639253c8198.png)

![image](https://user-images.githubusercontent.com/71147956/222650672-ae45b5ea-5628-4094-befd-d951d5140326.png)

**Comment by rudSarkar** [comment] 2023-03-03 23:18
This is not a bug because there is an option to "**force http on rawdata mode**". Find the below reference the HTTP by default is set to false, If you need to send the HTTP request please use **`--http`** so you can send a request via HTTP.

#### Command for force HTTP on rawdata mode
```bash
dalfox file --rawdata raw_request.txt --http --poc-type=http-request
```

#### Output
<img width="1418" alt="Screenshot 2023-03-04 at 5 16 51 AM" src="https://user-images.githubusercontent.com/20747656/222853045-d937b325-b42e-4bfc-bb67-00b8221b9618.png">


#### Reference
https://github.com/hahwul/dalfox/blob/efcef0ffbf0fe775d8722940cce02069d7b51fdb/cmd/file.go#L267

Please @hahwul close this issue.

**Comment by hahwul** [comment] 2023-03-04 16:55
Hi @darshanpjpt 
As @rudSarkar explained, when using rawdata, it is basically recognized as HTTPS and can be fixed as HTTP through flag. This is because you cannot identify whether HTTP or HTTPS was used in the Raw HTTP request.

As it is not a bug, I will close the issue. If there's a problem, please re-open it again :D

**Closed by hahwul** 2023-03-04 16:55 UTC
Labels: question
